### ISSUE TITLE
Question regarding use of U9 in revB schematic

### ISSUE THREAD

**Issue by l0rdl4nx** [Misaka0x2730/MioLink#1]
Hi,

I really like your  project and am rebuilding it myself at the moment. 
Since I will be using other level shifters (I got some unidirectional high speed ones lying around + some BBS138's), I was wondering about your level-shifter designs. For TMS/SWDIO you are using another 74LVCT45DC (U9). Is there any specific reason for that (switching speed?), would just a BBS138 not be sufficient?
I'm not quite stocked about having to order for just that part, because I basically have everything else at hand...

A quick reply would be appreciated :)

**Comment by Misaka0x2730** [comment]
Hi!
Yeah, the switching speed is the main reason (and the occupied space on the PCB is the second reason).
For example, if you use BS138 in the classic level shifter schematic on N-MOSFET (on the screenshot), then there is no problem with logic 0, but logic 1 is set on the line by only pull-ups, so there may be problems with rising edge (from 0 to 1) at high frequencies, since the line has a capacitance that will be recharged through these resistors.
![image](https://github.com/user-attachments/assets/f2291355-aa2b-43db-b992-d71cb712426a)

The SWD/JTAG level shiter schematic I implemented in rev. A and rev. B is generally standard. If you need another reference, you can check the Black Magic Probe schematic [here](https://black-magic.org/hardware.html).

**Comment by l0rdl4nx** [comment]
Thanks for your (I have to admit, **very** quick) reply :)

That circuit was exactly what I was thinking about. But sure, if the switching frequency doesn't allow for it I probably have to get some of those translator chips. Just out of curiosity, what exactly does the SWDIO use for a switching frequency/data rate (JTAG TMS frequency is low enough as far as I know)?
BSS138 datasheet says something around 20-40ns switching time, the actual rise time in circuit is propably quite a bit higher...

Also, I will still propably adapt the circuit to accomnodate the [TXU0204](https://www.ti.com/lit/ds/symlink/txu0204-q1.pdf?ts=1729106228717), just because I have enough of them and don't need them any time soon.

**Comment by Misaka0x2730** [comment]
You're right, the JTAG TMS frequency is not very high, but the TCK frequency is high and since the JTAG interface is synchronous, then the correct level must be set on the TMS line before a front on the TCK line. In other words, it's not the frequency that matters, but the slew rate.
And the second, most important point is that the TMS line is the SWDIO line in the SWD mode and in this case the frequency there is very high. And that's why we need to control the TMS pin direction. So, if you don't need to support the SWD mode in your project, then you can just use TXU0204 on all lines.

**Comment by l0rdl4nx** [comment]
Oh yea, I can see what you mean. Even without the capacitance of the traces and the resistors it looks horrible... (pulse @ 100MHz)
![image](https://github.com/user-attachments/assets/c5f97726-181a-4e4e-9ddc-7cfcc08842e4)
![schematic](https://github.com/user-attachments/assets/682172d4-f3bd-4dff-a238-68a2164f3e4b)

Still looking for a spice model of the TXU0204, I just want to see how it would react if I "daisy-chain" two channels with high frequency diodes ([BAS32L](https://assets.nexperia.com/documents/data-sheet/BAS32L.pdf)), to make bi-unidirectional channel.

Nvtl I will propably just get a 74LVCT45DC's for SWDIO; my main focus is to debug other RP2040s so I need the SWD interface.

**Comment by Misaka0x2730** [comment]
Exactly, I simulated it with 2N7002 and even without significant load on 1MHz it will never reach 5V on the high side 
![image](https://github.com/user-attachments/assets/7361d94a-8a66-49d4-a983-cc0fa2477670)

With small capacitance it will look even worse:
![image](https://github.com/user-attachments/assets/18d19de0-f586-4078-86c5-5acd80316a53)

**Comment by Misaka0x2730** [comment]
There is one way you can improve the edge response - reduce R1 and R2 value, with 1kOhm it will work on 1MHz
![image](https://github.com/user-attachments/assets/090c89f8-1cbf-4b29-a152-4e8cffac1f19)

**Comment by l0rdl4nx** [comment]
Oh sorry, I completly forgot to close it as completed.

I didn't have that much time on the weekend, but I'm planning on doing some more work on my own PCB in the next days. In theory and according to the datasheet I _should_ be able to do something like that:
![image](https://github.com/user-attachments/assets/d33c61fa-bf7b-4f29-bced-4e91908c148c)

Never the less I will propably still go the "save" route and use your (BMP is using the exact same I believe) proven as working design; just to be sure that's not the point of failure xD

Thanks a lot for your help here and especially for releasing your work as open-source.
